export type MarketingPage = {
  slug: string;
  title: string;
  eyebrow: string;
  description: string;
  sections: readonly { title: string; body: string }[];
  legalReview: boolean;
};

const page = (slug: string, title: string, eyebrow: string, description: string, sections: MarketingPage["sections"], legalReview = false): MarketingPage => ({ slug, title, eyebrow, description, sections, legalReview });

export const marketingPages = [
  page("product", "A clearer way to understand the news", "Product", "NyaVista is being designed to organize multi-source context, accessible explainers, and source transparency in one global experience.", [{ title: "One developing story, clearer context", body: "The planned product groups related reporting, preserves source paths, and separates confirmed facts from uncertainty." }, { title: "Built for different moments", body: "Readable, audio, and video formats are planned without presenting this local demonstration as a live service." }]),
  page("features", "Clarity, transparency, and choice", "Features", "Explore the capabilities planned for NyaVista. Current screens use fictional data and no live providers.", [{ title: "Multi-source intelligence", body: "Compare reporting signals and understand meaningful differences without flattening geographic or editorial nuance." }, { title: "Accessible multimedia", body: "Planned explainers include captions, transcripts, source attribution, and human review before publication." }]),
  page("how-it-works", "From source signals to reviewed context", "How it works", "A transparent overview of the planned rights-aware and human-reviewed workflow.", [{ title: "Collect and validate", body: "Authorized providers will be validated, normalized, deduplicated, and checked against source-specific rights rules." }, { title: "Cluster and review", body: "Related coverage may be grouped and summarized through schema-validated AI assistance, with configured human review for sensitive material." }]),
  page("global-coverage", "Global coverage, country-neutral standards", "Global coverage", "Commercial launch priorities never determine editorial importance.", [{ title: "Consistent geography architecture", body: "Countries and regions use shared identifiers and qualification standards rather than permanent special-case ranking." }, { title: "Local context matters", body: "Planned coverage analytics surface source concentration, translation reliance, and local-versus-international balance." }]),
  page("video-explainers", "Visual briefings with context", "Video explainers", "Planned video experiences prioritize clarity, captions, transcripts, attribution, and rights-cleared media.", [{ title: "Accessible by default", body: "Captions, transcripts, keyboard controls, and reduced-motion considerations are required before production release." }, { title: "Reviewed before publishing", body: "Generated scripts and visuals are planned to remain draft material until required editorial and rights checks pass." }]),
  page("audio-briefings", "Listen without losing the source trail", "Audio briefings", "Planned audio briefings pair concise narration with transcripts, attribution, and correction history.", [{ title: "Multiple formats", body: "Users will be able to choose formats appropriate to their time, bandwidth, and accessibility needs." }, { title: "Truthful provider state", body: "No text-to-speech or audio provider is connected in this local demonstration." }]),
  page("professionals", "News intelligence for focused work", "For professionals", "Planned professional workflows emphasize traceability, efficient review, and configurable monitoring.", [{ title: "Transparent context", body: "Source counts, uncertainty, corrections, and original links remain visible rather than hidden behind an opaque score." }, { title: "Not financial or legal advice", body: "NyaVista information products will require appropriate disclaimers and should not replace qualified professional advice." }]),
  page("organizations", "Shared intelligence without shared blind spots", "For organizations", "Organization capabilities are planned around configurable access, auditability, and least privilege.", [{ title: "Controlled collaboration", body: "Future organization features require server-enforced roles, auditable actions, and explicit data boundaries." }, { title: "Provider-neutral architecture", body: "External services remain replaceable and must expose configuration, failure, and cost state truthfully." }]),
  page("pricing", "Pricing is not yet available", "Pricing", "NyaVista has not published production plans or prices. This page prevents fictional commercial claims while the product is in development.", [{ title: "No active subscriptions", body: "Checkout, billing, entitlements, and payment providers are not connected in this demonstration." }, { title: "Future transparency", body: "Any future plan will clearly explain included capabilities, renewal terms, cancellation, and applicable taxes before purchase." }]),
  page("about", "United States-founded. Built for a global audience.", "About", "NyaVista is a proprietary product of E-DEAL EXPRESS LLC, a United States company.", [{ title: "Global and country-neutral", body: "The Eʋe-inspired name reflects brand heritage, not regional exclusivity or editorial priority." }, { title: "A clearer view", body: "The product is being developed around multi-source transparency, human review, accessible formats, and geographic fairness." }]),
  page("newsletter", "Newsletter delivery is not active", "Newsletter", "Newsletter preferences and delivery providers are planned but are not connected in this demonstration.", [{ title: "Consent before delivery", body: "Future signup requires clear consent, unsubscribe controls, preference management, and observable delivery failures." }, { title: "No form yet", body: "We do not collect an email address here until secure storage, privacy notices, and deletion handling are implemented." }]),
  page("contact", "Contact channels are being finalized", "Contact", "A verified public contact address has not been configured, so this page does not invent one.", [{ title: "No data collection", body: "This demonstration does not submit or store contact messages." }, { title: "Required launch contacts", body: "General support, privacy, legal, accessibility, corrections, and rights-removal channels must be verified before launch." }]),
  page("faq", "Questions about the NyaVista demonstration", "FAQ", "Direct answers about what is implemented today and what remains planned.", [{ title: "Is this live news?", body: "No. All visible stories, metrics, sources, queues, and provider states are fictional planning material." }, { title: "Does AI publish automatically?", body: "No. Production AI workflows require structured validation, attribution, audit records, and configured human review." }]),
  page("editorial-standards", "Editorial standards — review draft", "Trust and editorial", "This development-stage outline requires qualified editorial and legal review before launch.", [{ title: "Core commitments", body: "Planned standards include accuracy, nonpartisanship, source transparency, uncertainty labels, correction history, and consistent geographic treatment." }, { title: "Sensitive coverage", body: "Elections, health, violence, allegations, security, borders, and other high-risk subjects require configurable elevated review." }], true),
  page("source-methodology", "Source methodology — review draft", "Trust and editorial", "This shell describes intended controls and is not a final source-admission policy.", [{ title: "Consistent qualification", body: "Sources should be assessed through documented, consistently applied criteria rather than nationality, market priority, or country size." }, { title: "Rights and attribution", body: "Each source requires explicit rights rules, attribution requirements, permitted storage, and removal handling." }], true),
  page("recommendation-methodology", "Recommendation methodology — review draft", "Trust and editorial", "Recommendations are not active. This outline records the intended transparency and fairness baseline.", [{ title: "User control", body: "Future personalization must be understandable, reversible, and must not infer nationality from location without consent." }, { title: "Fairness checks", body: "Testing must detect automatic suppression of non-priority countries and expose source and geography concentration." }], true),
  page("ai-disclosure", "Content and AI disclosure — review draft", "Trust and editorial", "No live AI provider is connected. Future assistance must be labeled, auditable, validated, and subject to required review.", [{ title: "AI assists; it does not establish truth", body: "Outputs must remain grounded in authorized source material and distinguish confirmed, uncertain, and disputed claims." }, { title: "Operational transparency", body: "Provider, model, prompt version, request identifier, usage, cost, and reviewer metadata are planned audit fields." }], true),
  page("corrections", "Corrections process — review draft", "Trust and editorial", "There are no live publications to correct. A public, auditable correction process is required before launch.", [{ title: "Visible history", body: "Material changes should record what changed, when, why, and the responsible review action." }, { title: "Reporting channel pending", body: "A verified corrections contact and secure workflow have not yet been configured." }], true),
  page("copyright-dmca", "Copyright and DMCA — legal review draft", "Legal", "This placeholder is not legal advice and requires qualified United States legal review plus verified agent/contact details.", [{ title: "Rights-aware design", body: "NyaVista must not bypass paywalls, default to storing unauthorized full text, or use unlicensed publisher media." }, { title: "Notice process pending", body: "A production notice-and-takedown process cannot launch until verified contact, identity, logging, and response procedures exist." }], true),
  page("privacy", "Privacy notice — legal review draft", "Legal", "No account, contact, analytics, or personalization data is collected by this local demonstration.", [{ title: "Current demonstration", body: "There is no production database, authentication, newsletter submission, payment flow, or advertising integration in this build." }, { title: "Before production", body: "Data categories, purposes, legal bases, retention, deletion, regional notices, subprocessors, and user rights require implementation and qualified review." }], true),
  page("terms", "Terms of use — legal review draft", "Legal", "These are not operative terms. Qualified counsel must approve final terms before a public service is offered.", [{ title: "Development preview", body: "The current experience is fictional, local, non-production, and supplied without live reporting or provider availability." }, { title: "Final terms pending", body: "Eligibility, acceptable use, subscriptions, intellectual property, disclaimers, disputes, termination, and governing-law provisions remain unapproved." }], true),
  page("cookies", "Cookie notice — legal review draft", "Legal", "The current application does not intentionally configure advertising or analytics cookies.", [{ title: "Essential runtime behavior", body: "Development tooling may use local runtime storage; that is not a production consent implementation." }, { title: "Consent architecture pending", body: "Any non-essential production storage requires classification, region-aware consent, preference withdrawal, and verified vendor documentation." }], true),
  page("community-guidelines", "Community guidelines — review draft", "Legal and community", "Community participation is not implemented. These principles require policy, moderation, appeal, and legal review.", [{ title: "Respectful participation", body: "Future community tools should prohibit abuse, manipulation, doxxing, and unlawful or rights-infringing material." }, { title: "Fair enforcement", body: "Moderation decisions require documented rules, proportionate action, auditable history, and an appropriate appeal path." }], true),
  page("accessibility", "Accessibility commitment — review draft", "Accessibility", "NyaVista targets WCAG 2.2 AA and treats accessibility as an ongoing product requirement.", [{ title: "Current foundation", body: "Semantic structure, visible focus, reduced motion, responsive layouts, and native controls are included in the present demonstration." }, { title: "Further validation", body: "Screen-reader certification, cross-browser testing, captions, transcripts, localization, and a verified feedback channel remain required before launch." }], true),
] as const satisfies readonly MarketingPage[];

export const marketingPageBySlug = new Map(marketingPages.map((item) => [item.slug, item]));

export function getMarketingPage(slug: string): MarketingPage | undefined {
  return marketingPageBySlug.get(slug);
}

export function resolveProductionOrigin(value: string | undefined): string | null {
  if (!value) return null;
  try {
    const url = new URL(value);
    if (url.protocol !== "https:" || url.username || url.password || url.pathname !== "/" || url.search || url.hash) return null;
    return url.origin;
  } catch {
    return null;
  }
}
